//! Tests for the native AVIF container and AV1 header parsers.
//!
//! Fixtures in `tests/data/` are generated by `tests/gen_avif.py` with
//! `avifenc` (libavif, aom encoder). The reference PNG files next to them are
//! decoded by libavif and are only used once the AV1 tile decoder lands.

use coreimage::codecs::av1::{self, ChromaFormat, SequenceHeader};
use coreimage::codecs::avif;
use coreimage::{ImageFormat, TiImage};

fn data(name: &str) -> Vec<u8> {
    std::fs::read(format!("tests/data/{name}")).expect("fixture")
}

fn png(name: &str) -> Vec<u8> {
    std::fs::read(format!("tests/data/{name}")).expect("fixture")
}

// -- Magic detection --

#[test]
fn detects_avif_files() {
    for name in [
        "avif_420_q60.avif",
        "avif_444_q70.avif",
        "avif_lossless.avif",
        "avif_10bit_420.avif",
        "avif_alpha.avif",
    ] {
        assert!(avif::is_avif(&data(name)), "{name} not detected");
    }
}

#[test]
fn rejects_other_formats() {
    assert!(!avif::is_avif(&data("ref_32bit.ico")));
    assert!(!avif::is_avif(&data("avif_420_q60.png")));
    assert!(!avif::is_avif(b"not an avif file at all"));
}

// -- Container overview --

#[test]
fn probe_reports_sizes_and_depths() {
    let cases: [(&str, u32, u32, u8, ChromaFormat); 11] = [
        ("avif_420_q60.avif", 96, 64, 8, ChromaFormat::Cs420),
        ("avif_444_q70.avif", 96, 64, 8, ChromaFormat::Cs444),
        ("avif_422_q70.avif", 96, 64, 8, ChromaFormat::Cs422),
        ("avif_mono_q70.avif", 64, 48, 8, ChromaFormat::Monochrome),
        ("avif_lossless.avif", 96, 64, 8, ChromaFormat::Cs444),
        ("avif_10bit_420.avif", 96, 64, 10, ChromaFormat::Cs420),
        ("avif_tiles.avif", 96, 64, 8, ChromaFormat::Cs420),
        ("avif_odd_37x23.avif", 37, 23, 8, ChromaFormat::Cs444),
        ("avif_screenc.avif", 96, 64, 8, ChromaFormat::Cs420),
        ("avif_alpha.avif", 64, 48, 8, ChromaFormat::Cs444),
        ("avif_edge_q80.avif", 96, 64, 8, ChromaFormat::Cs420),
    ];
    for (name, w, h, depth, chroma) in cases {
        let bytes = data(name);
        let info = avif::probe(&bytes).expect(name);
        assert_eq!((info.width, info.height), (w, h), "{name} size");
        assert_eq!(info.chroma_format, chroma, "{name} chroma");
        assert_eq!(
            info.depths.first().copied(),
            Some(depth),
            "{name} depth {:?}",
            info.depths
        );
        assert_eq!(avif::dimensions(&bytes).expect(name), (w, h), "{name} dimensions");
    }
}

#[test]
fn probe_finds_colour_description() {
    let info = avif::probe(&data("avif_420_q60.avif")).unwrap();
    let colour = info.colour.expect("nclx colr box");
    assert_eq!(colour.primaries, 1);
    assert_eq!(colour.transfer, 13);
    assert!(colour.full_range);
}

#[test]
fn probe_finds_alpha_item() {
    let bytes = data("avif_alpha.avif");
    let info = avif::probe(&bytes).unwrap();
    let alpha = info.alpha_item.expect("alpha aux item");
    assert!(alpha != 0);
    // The alpha item is an AV1 image of the same size as the primary item.
    let obus = avif::aux_obus(&bytes, alpha).expect("alpha obus");
    let seq = av1::parse_sequence_header(&obus).expect("alpha sequence header");
    assert_eq!((seq.max_width(), seq.max_height()), (64, 48));
    assert!(seq.mono_chrome, "alpha item is monochrome");
}

#[test]
fn probe_rejects_truncated_file() {
    let bytes = data("avif_420_q60.avif");
    let cut = &bytes[..bytes.len() / 2];
    assert!(avif::probe(cut).is_err());
}

#[test]
fn probe_rejects_non_avif() {
    assert!(avif::probe(&data("ref_32bit.ico")).is_err());
    assert!(avif::dimensions(&data("ref_32bit.ico")).is_err());
}

// -- AV1 headers --

fn headers(name: &str) -> (SequenceHeader, Option<coreimage::codecs::av1::FrameHeader>) {
    let bytes = data(name);
    let obus = avif::item_obus(&bytes).expect(name);
    let h = av1::parse_headers(&obus).expect(name);
    (h.sequence, h.frame)
}

#[test]
fn sequence_header_matches_container() {
    let cases = [
        ("avif_420_q60.avif", 8u32, ChromaFormat::Cs420),
        ("avif_444_q70.avif", 8, ChromaFormat::Cs444),
        ("avif_10bit_420.avif", 10, ChromaFormat::Cs420),
        ("avif_mono_q70.avif", 8, ChromaFormat::Monochrome),
    ];
    for (name, depth, chroma) in cases {
        let (seq, _) = headers(name);
        assert_eq!(seq.bit_depth, depth, "{name} bit depth");
        assert_eq!(seq.chroma_format(), chroma, "{name} chroma");
    }
}

#[test]
fn frame_header_matches_ispe_and_pixi() {
    for name in [
        "avif_420_q60.avif",
        "avif_444_q70.avif",
        "avif_422_q70.avif",
        "avif_mono_q70.avif",
        "avif_tiles.avif",
        "avif_odd_37x23.avif",
        "avif_edge_q80.avif",
    ] {
        let bytes = data(name);
        let info = avif::probe(&bytes).expect(name);
        let (_, frame) = headers(name);
        let frame = frame.unwrap_or_else(|| panic!("{name} has no frame header"));
        assert_eq!(frame.frame_width, info.width, "{name} frame width");
        assert_eq!(frame.frame_height, info.height, "{name} frame height");
        assert_eq!(frame.render_width, info.width, "{name} render width");
        assert_eq!(frame.render_height, info.height, "{name} render height");
        assert!(!frame.allow_intrabc, "{name} intrabc");
        assert!(frame.mi_col_starts.len() > 1, "{name} mi cols");
        assert!(frame.mi_row_starts.len() > 1, "{name} mi rows");
    }
}

#[test]
fn frame_header_reports_tiles() {
    let (_, plain) = headers("avif_420_q60.avif");
    let plain = plain.unwrap();
    assert_eq!((plain.tile_cols, plain.tile_rows), (1, 1));
    let (_, tiled) = headers("avif_tiles.avif");
    let tiled = tiled.unwrap();
    // 96x64 gives two superblock columns and one row with 64x64 superblocks,
    // so two tile columns are possible and two tile rows are not.
    assert_eq!((tiled.tile_cols, tiled.tile_rows), (2, 1));
    assert!(tiled.tile_cols_log2 > 0);
    assert!(tiled.tile_size_bytes > 0);
}

#[test]
fn frame_header_reports_loop_filters() {
    let (seq, frame) = headers("avif_edge_q80.avif");
    let frame = frame.unwrap();
    assert!(frame.loop_filter_level[0] > 0, "deblocking enabled");
    assert!(frame.cdef_bits > 0, "cdef enabled");
    // Loop restoration follows the sequence header enable flag.
    assert_eq!(frame.uses_lr, seq.enable_restoration && !frame.all_lossless);
}

#[test]
fn tile_layout_covers_every_tile() {
    // One tile per frame, sized from the OBU payload.
    let bytes = data("avif_420_q60.avif");
    let layout = avif::tile_layout(&bytes).expect("tile layout");
    assert_eq!(layout.tile_count(), 1);
    assert_eq!((layout.frame.tile_cols, layout.frame.tile_rows), (1, 1));
    let tile = &layout.tiles[0];
    assert_eq!((tile.row, tile.col), (0, 0));
    assert_eq!(tile.mi_row_start, 0);
    assert_eq!(tile.mi_row_end, layout.frame.mi_rows);
    assert_eq!(tile.mi_col_start, 0);
    assert_eq!(tile.mi_col_end, layout.frame.mi_cols);
    assert!(tile.size > 0, "tile carries entropy coded data");
    assert_eq!(layout.coded_bytes(), tile.size);
}

#[test]
fn tile_layout_splits_two_tile_columns() {
    // 96x64 allows two tile columns and one tile row.
    let bytes = data("avif_tiles.avif");
    let layout = avif::tile_layout(&bytes).expect("tile layout");
    assert_eq!(layout.tile_count(), 2);
    assert!(layout.frame.tile_size_bytes >= 1);
    let first = &layout.tiles[0];
    let second = &layout.tiles[1];
    assert_eq!((first.row, first.col), (0, 0));
    assert_eq!((second.row, second.col), (0, 1));
    assert_eq!(first.mi_col_end, second.mi_col_start);
    assert_eq!(first.mi_rows_range(), layout.frame.mi_rows);
    assert!(first.size > 0 && second.size > 0, "both tiles carry data");
    // Tile bytes never overlap and stay inside the OBU payload.
    assert_eq!(first.offset + first.size, second.offset);
}

#[test]
fn tile_layout_matches_frame_headers() {
    for name in [
        "avif_444_q70.avif",
        "avif_422_q70.avif",
        "avif_odd_37x23.avif",
        "avif_edge_q80.avif",
        "avif_mono_q70.avif",
    ] {
        let bytes = data(name);
        let layout = avif::tile_layout(&bytes).expect(name);
        assert_eq!(layout.tile_count(), layout.frame.tile_cols * layout.frame.tile_rows, "{name}");
        let expected_mi_cols = ((layout.frame.frame_width + 3) / 4) as usize;
        assert_eq!(layout.tiles[0].mi_width(), expected_mi_cols, "{name}");
    }
}

// -- Library integration --

#[test]
fn metadata_reports_avif() {
    let bytes = data("avif_10bit_420.avif");
    let meta = coreimage::io::metadata_from_bytes(&bytes).expect("metadata");
    assert_eq!(meta.format, Some(ImageFormat::Avif));
    assert_eq!((meta.width, meta.height), (96, 64));
    assert_eq!(meta.color_type, "AV1-40420");
}

#[test]
fn probe_format_detects_avif() {
    let bytes = data("avif_420_q60.avif");
    assert_eq!(ImageFormat::from_extension("x.avif"), Some(ImageFormat::Avif));
    assert_eq!(ImageFormat::from_extension("x.avis"), Some(ImageFormat::Avif));
    assert_eq!(ImageFormat::from_magic(&bytes), Some(ImageFormat::Avif));
    assert_eq!(
        coreimage::io::probe_format_from_bytes(&bytes).unwrap(),
        ImageFormat::Avif
    );
}

#[test]
fn pixel_decode_is_reported_as_unsupported() {
    // The AV1 tile decoder is not part of this crate yet: the container and
    // headers decode, the pixels return a localized Unsupported error.
    let bytes = data("avif_420_q60.avif");
    match TiImage::from_bytes(&bytes) {
        Err(coreimage::ImageError::Unsupported(_)) => {}
        other => panic!("expected Unsupported, got {other:?}"),
    }
}

#[test]
fn avif_encode_is_reported_as_unsupported() {
    let png_bytes = png("avif_420_q60.png");
    let img = TiImage::from_bytes(&png_bytes).expect("png");
    match img.to_bytes(ImageFormat::Avif, 90) {
        Err(coreimage::ImageError::Unsupported(_)) => {}
        other => panic!("expected Unsupported, got {other:?}"),
    }
}

// -- Reference images stay untouched --

#[test]
fn reference_pngs_have_expected_sizes() {
    for (name, w, h) in [
        ("avif_420_q60.png", 96u32, 64u32),
        ("avif_odd_37x23.png", 37, 23),
        ("avif_alpha.png", 64, 48),
    ] {
        let img = TiImage::from_bytes(&png(name)).expect(name);
        assert_eq!(img.dimensions(), (w, h), "{name}");
    }
}