//! Tests for the pure-Rust JPEG codec (`src/codecs/jpeg.rs`).
//!
//! Reference fixtures in `tests/data/` are generated by Pillow
//! (see `gen_jpeg.py` in the temp dir used during development).
//! Lossy comparisons use max/mean absolute difference.

use coreimage::codecs::jpeg;
use coreimage::codecs::jpeg::JpegSampling;

fn data(name: &str) -> Vec<u8> {
    let path = format!("{}/tests/data/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read(&path).unwrap_or_else(|_| panic!("missing fixture {path}"))
}

fn image_decode(bytes: &[u8]) -> (u32, u32, Vec<u8>) {
    let img = image::load_from_memory(bytes).expect("image crate decode").to_rgba8();
    let (w, h) = (img.width(), img.height());
    (w, h, img.into_raw())
}

fn max_diff(a: &[u8], b: &[u8]) -> u8 {
    a.iter().zip(b.iter()).map(|(x, y)| x.abs_diff(*y)).max().unwrap_or(0)
}

fn mean_diff(a: &[u8], b: &[u8]) -> f32 {
    let sum: u64 = a.iter().zip(b.iter()).map(|(x, y)| x.abs_diff(*y) as u64).sum();
    sum as f32 / a.len() as f32
}

fn gradient_rgba(w: u32, h: u32) -> Vec<u8> {
    let mut px = Vec::with_capacity((w * h * 4) as usize);
    for y in 0..h {
        for x in 0..w {
            px.extend_from_slice(&[
                ((x * 4 + y * 2) % 256) as u8,
                ((y * 5 + x) % 256) as u8,
                (((x * x + y * y) / 7) % 256) as u8,
                255,
            ]);
        }
    }
    px
}

// ── PIL fixtures vs `image` crate ─────────────────────────────

#[test]
fn fixture_baseline_matches_reference() {
    for name in [
        "baseline_420_q75_exif.jpg",
        "baseline_422_q80.jpg",
        "baseline_444_q90.jpg",
        "gray_q75.jpg",
        "odd_37x23_q75.jpg",
    ] {
        let bytes = data(name);
        assert!(jpeg::is_jpeg(&bytes), "{name}");
        let ours = jpeg::decode(&bytes).unwrap_or_else(|e| panic!("{name}: {e}"));
        let (w, h, tie) = image_decode(&bytes);
        assert_eq!((ours.width, ours.height), (w, h), "{name} dims");
        assert_eq!(jpeg::dimensions(&bytes), Ok((w, h)), "{name} probe");
        let md = max_diff(&ours.pixels, &tie);
        let ad = mean_diff(&ours.pixels, &tie);
        // Bounds reflect legitimate cross-implementation variance
        // (float IDCT rounding, bilinear vs fancy chroma upsampling):
        // means stay tiny, maxima sit on sharp chroma edges.
        let (max_bound, mean_bound) = match name {
            "odd_37x23_q75.jpg" => (60, 4.0),
            "baseline_420_q75_exif.jpg" => (25, 1.5),
            "baseline_422_q80.jpg" => (10, 1.5),
            "baseline_444_q90.jpg" => (4, 1.0),
            _ => (2, 0.5), // gray
        };
        assert!(md <= max_bound, "{name} max diff {md}");
        assert!(ad <= mean_bound, "{name} mean diff {ad}");
    }
}

#[test]
fn fixture_exif_metadata() {
    let bytes = data("baseline_420_q75_exif.jpg");
    let meta = coreimage::io::metadata_from_bytes(&bytes).expect("metadata");
    assert_eq!((meta.width, meta.height), (64, 48));
    assert_eq!(meta.exif_orientation, Some(6));
    assert!(meta.exif_camera.as_deref().unwrap_or_default().contains("Tontoo"));
    assert!(meta.exif_date_taken.as_deref().unwrap_or_default().contains("2026"));
}

#[test]
fn fixture_progressive_and_cmyk_unsupported() {
    let prog = data("progressive_q75.jpg");
    assert!(jpeg::is_jpeg(&prog));
    // Dimensions probe works even though decode is unsupported.
    assert_eq!(jpeg::dimensions(&prog), Ok((64, 48)));
    assert!(matches!(
        jpeg::decode(&prog),
        Err(jpeg::JpegError::Unsupported(_))
    ));
    let cmyk = data("cmyk_q75.jpg");
    assert!(matches!(
        jpeg::decode(&cmyk),
        Err(jpeg::JpegError::Unsupported(_))
    ));
}

// ── Roundtrips ────────────────────────────────────────────────

/// Smooth linear ramps (DCT-friendly, no chroma torture edges).
fn smooth_rgba(w: u32, h: u32) -> Vec<u8> {
    let mut px = Vec::with_capacity((w * h * 4) as usize);
    for y in 0..h {
        for x in 0..w {
            px.extend_from_slice(&[
                (x * 255 / (w - 1).max(1)) as u8,
                (y * 255 / (h - 1).max(1)) as u8,
                (((x + y) * 255) / (w + h - 2).max(1)) as u8,
                255,
            ]);
        }
    }
    px
}

#[test]
fn roundtrip_quality_series() {
    let (w, h) = (64u32, 48u32);
    let px = smooth_rgba(w, h);
    let mut sizes = Vec::new();
    let mut maxes = Vec::new();
    for q in [95u8, 75, 50, 20] {
        let enc = jpeg::encode(w, h, &px, q).expect("encode");
        let dec = jpeg::decode(&enc).expect("decode");
        assert_eq!((dec.width, dec.height), (w, h));
        sizes.push(enc.len());
        maxes.push(max_diff(&dec.pixels, &px));
    }
    assert!(sizes[0] > sizes[1] && sizes[1] > sizes[2] && sizes[2] > sizes[3], "{sizes:?}");
    assert!(maxes[0] <= 12, "q95 max {:?}", maxes[0]);
    assert!(maxes[3] >= maxes[0], "endpoints ordered {maxes:?}");
    assert!(maxes[3] >= 5, "sanity: q=20 must show visible loss");
}

#[test]
fn roundtrip_444_sharper_than_420() {
    // Hard red/blue bars punish chroma subsampling.
    let (w, h) = (48u32, 32u32);
    let mut px = Vec::new();
    for y in 0..h {
        for x in 0..w {
            if (x / 2 + y) % 2 == 0 {
                px.extend_from_slice(&[220, 20, 30, 255]);
            } else {
                px.extend_from_slice(&[30, 40, 220, 255]);
            }
        }
    }
    let e444 = jpeg::encode_with_sampling(w, h, &px, 75, JpegSampling::Yuv444).unwrap();
    let e420 = jpeg::encode_with_sampling(w, h, &px, 75, JpegSampling::Yuv420).unwrap();
    assert!(e420.len() < e444.len(), "420 must be smaller");
    let d444 = jpeg::decode(&e444).unwrap();
    let d420 = jpeg::decode(&e420).unwrap();
    assert!(max_diff(&d444.pixels, &px) <= max_diff(&d420.pixels, &px));
}

#[test]
fn roundtrip_odd_sizes() {
    // Loss bounds grow on tiny images (whole-image single blocks,
    // 4:2:0 chroma); same-file agreement stays tight throughout.
    for (w, h, bound) in [(37u32, 23u32, 12), (7, 5, 45), (1, 1, 0), (16, 9, 20)] {
        let px = smooth_rgba(w, h);
        let enc = jpeg::encode(w, h, &px, 75).expect("encode");
        let dec = jpeg::decode(&enc).expect("decode");
        assert_eq!((dec.width, dec.height), (w, h), "{w}x{h}");
        assert!(max_diff(&dec.pixels, &px) <= bound, "{w}x{h}");
        // The `image` crate agrees on our files (same-file comparison).
        let (_, _, tie) = image_decode(&enc);
        assert!(max_diff(&dec.pixels, &tie) <= 10, "{w}x{h} interop");
    }
}

#[test]
fn grayscale_fast_path() {
    let (w, h) = (32u32, 24u32);
    let gray: Vec<u8> = (0..w * h).map(|i| ((i * 255) / (w * h - 1)) as u8).collect();
    let enc = jpeg::encode_grayscale(w, h, &gray, 80).expect("encode");
    let dec = jpeg::decode(&enc).expect("decode");
    assert_eq!((dec.width, dec.height), (w, h));
    for (i, px) in dec.pixels.chunks_exact(4).enumerate() {
        assert_eq!(px[0], px[1], "r==g at {i}");
        assert_eq!(px[1], px[2], "g==b at {i}");
        assert_eq!(px[3], 255);
        assert!((px[0] as i32 - gray[i] as i32).abs() <= 12, "gray value at {i}");
    }
    // The `image` crate reads our gray files too.
    let (_, _, tie) = image_decode(&enc);
    assert!(max_diff(&dec.pixels, &tie) <= 8);
}

// ── Cross-checks vs `image` crate ─────────────────────────────

#[test]
fn image_encode_decoded_by_us() {
    use image::{DynamicImage, ImageFormat, RgbaImage};
    let (w, h) = (48u32, 36u32);
    let px = gradient_rgba(w, h);
    let buf = RgbaImage::from_raw(w, h, px.clone()).unwrap();
    let mut out = std::io::Cursor::new(Vec::new());
    let mut enc = image::codecs::jpeg::JpegEncoder::new_with_quality(&mut out, 85);
    use image::ImageEncoder as _;
    enc.encode_image(&DynamicImage::ImageRgba8(buf)).unwrap();
    let bytes = out.into_inner();
    let dec = jpeg::decode(&bytes).expect("our decode");
    assert_eq!((dec.width, dec.height), (w, h));
    // Same-file agreement is tight; both legitimately blur chroma edges.
    let (_, _, tie) = image_decode(&bytes);
    assert!(max_diff(&dec.pixels, &tie) <= 25);
    assert!(mean_diff(&dec.pixels, &tie) <= 2.0);
    assert!(max_diff(&dec.pixels, &px) <= 80);
}

#[test]
fn our_encode_decoded_by_image() {
    let (w, h) = (48u32, 36u32);
    let px = gradient_rgba(w, h);
    let enc = jpeg::encode(w, h, &px, 80).expect("encode");
    let dec = jpeg::decode(&enc).expect("our decode");
    let (_, _, tie) = image_decode(&enc);
    assert!(max_diff(&tie, &dec.pixels) <= 25);
    assert!(mean_diff(&tie, &dec.pixels) <= 2.0);
    // Torture gradients wrap chroma sharply; 4:2:0 downsampling aliases
    // those wraps (inherent, both decoders agree above). Reference: the
    // `image` crate's own q80 roundtrip also loses 92 here; our 444 loses 92.
    assert!(max_diff(&tie, &px) <= 200);
}

// ── Hand-built restart file ───────────────────────────────────

fn push_seg(out: &mut Vec<u8>, marker: u8, payload: &[u8]) {
    out.extend_from_slice(&[0xFF, marker]);
    out.extend_from_slice(&((payload.len() + 2) as u16).to_be_bytes());
    out.extend_from_slice(payload);
}

/// 16x16 gray image, DRI=2, all-zero blocks (DC 0 + EOB) with minimal
/// custom Huffman tables. Decodes to flat gray 128.
fn restart_fixture() -> Vec<u8> {
    let mut f = vec![0xFF, 0xD8];
    push_seg(&mut f, 0xE0, b"JFIF\0\x01\x02\x00\x00\x01\x00\x01\x00\x00");
    let mut dqt = vec![0x00];
    dqt.extend_from_slice(&[8u8; 64]);
    push_seg(&mut f, 0xDB, &dqt);
    push_seg(&mut f, 0xC0, &[8, 0, 16, 0, 16, 1, 1, 0x11, 0]);
    // Minimal DC table: one code (len 2, symbol 0).
    let mut dh = vec![0x00, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    push_seg(&mut f, 0xC4, &dh);
    dh[0] = 0x10;
    // Minimal AC table: one code (len 4, symbol 0x00 = EOB).
    dh[2] = 0;
    dh[4] = 1;
    dh[17] = 0x00;
    push_seg(&mut f, 0xC4, &dh);
    push_seg(&mut f, 0xDD, &[0, 2]);
    push_seg(&mut f, 0xDA, &[1, 1, 0, 0, 0x3F, 0]);
    // One block = DC "00" + EOB "0000" (canonical codes of the minimal
    // tables, 6 bits). Interval = 2 blocks, 1-filled to the byte.
    f.extend_from_slice(&[0x00, 0x0F, 0xFF, 0xD0, 0x00, 0x0F]);
    f.extend_from_slice(&[0xFF, 0xD9]);
    f
}

#[test]
fn restart_markers_decode() {
    let f = restart_fixture();
    let dec = jpeg::decode(&f).expect("restart decode");
    assert_eq!((dec.width, dec.height), (16, 16));
    assert!(dec.pixels.chunks_exact(4).all(|p| p == [128, 128, 128, 255]));
    // Independent agreement with the `image` crate.
    let (_, _, tie) = image_decode(&f);
    assert_eq!(tie, dec.pixels);
}

// ── Spliced / patched files ───────────────────────────────────

fn splice_after_soi(mut file: Vec<u8>, segments: &[&[u8]]) -> Vec<u8> {
    let mut head = file[..2].to_vec();
    for s in segments {
        head.extend_from_slice(s);
    }
    head.extend_from_slice(&file[2..]);
    file = head;
    file
}

fn app_segment(marker: u8, payload: &[u8]) -> Vec<u8> {
    let mut s = vec![0xFF, marker];
    s.extend_from_slice(&((payload.len() + 2) as u16).to_be_bytes());
    s.extend_from_slice(payload);
    s
}

#[test]
fn spliced_app_and_com_segments_skipped() {
    let (w, h) = (32u32, 24u32);
    let px = gradient_rgba(w, h);
    let base = jpeg::encode(w, h, &px, 75).unwrap();
    let expect = jpeg::decode(&base).unwrap().pixels;
    let mut app1 = b"Exif\0\0".to_vec();
    app1.extend_from_slice(&[0u8; 40]);
    let mut app14 = b"Adobe".to_vec();
    app14.extend_from_slice(&[0, 100, 0, 0, 0, 0, 1]); // version, flags, transform 1
    let file = splice_after_soi(
        base,
        &[&app_segment(0xE1, &app1), &app_segment(0xEE, &app14), &app_segment(0xFE, b"hello")],
    );
    let dec = jpeg::decode(&file).expect("spliced decode");
    assert_eq!(dec.pixels, expect);
}

fn find_sof_pos(file: &[u8]) -> usize {
    file.windows(2)
        .position(|w| w == [0xFF, 0xC0])
        .expect("SOF0 marker")
}

#[test]
fn patched_headers_rejected() {
    let px = gradient_rgba(24, 18);
    let base = jpeg::encode(24, 18, &px, 75).unwrap();
    let sof = find_sof_pos(&base);

    // Progressive SOF2.
    let mut f = base.clone();
    f[sof + 1] = 0xC2;
    assert!(matches!(jpeg::decode(&f), Err(jpeg::JpegError::Unsupported(_))));

    // 12-bit precision.
    let mut f = base.clone();
    f[sof + 4] = 12;
    assert!(matches!(jpeg::decode(&f), Err(jpeg::JpegError::Unsupported(_))));

    // 4 components (CMYK).
    let mut f = base.clone();
    f[sof + 9] = 4;
    assert!(matches!(jpeg::decode(&f), Err(jpeg::JpegError::Unsupported(_))));
}

#[test]
fn truncated_and_garbage_rejected() {
    assert!(!jpeg::is_jpeg(b""));
    assert!(!jpeg::is_jpeg(b"hello world"));
    assert!(jpeg::decode(b"").is_err());
    assert!(jpeg::decode(&[0xFF, 0xD8, 0xFF, 0xD9]).is_err());
    assert!(jpeg::dimensions(b"nope").is_err());

    let px = gradient_rgba(32, 24);
    let base = jpeg::encode(32, 24, &px, 75).unwrap();
    assert!(jpeg::decode(&base[..base.len() / 2]).is_err());
    assert!(jpeg::decode(&base[..base.len() - 4]).is_err());

    // Bad SOF marker byte inside header.
    let mut f = base.clone();
    let sof = find_sof_pos(&f);
    f[sof] = 0xFE;
    assert!(jpeg::decode(&f).is_err());

    // Encoder input validation.
    assert!(jpeg::encode(0, 8, &[], 75).is_err());
    assert!(jpeg::encode(4, 4, &[1, 2, 3], 75).is_err());
    assert!(jpeg::encode(4, 4, &vec![0u8; 64], 0).is_err());
    assert!(jpeg::encode(4, 4, &vec![0u8; 64], 101).is_err());
}
