//! Tests for the native WebP codec (`src/codecs/webp.rs`).
//!
//! Reference fixtures in `tests/data/` are generated by Pillow
//! (`tests/gen_webp.py`). Lossless fixtures compare bit-exact;
//! lossy fixtures use max/mean absolute difference.

use coreimage::codecs::webp;

fn data(name: &str) -> Vec<u8> {
    let path = format!("{}/tests/data/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read(&path).unwrap_or_else(|_| panic!("missing fixture {path}"))
}

fn ref_rgba(name: &str) -> (u32, u32, Vec<u8>) {
    let bytes = data(name);
    let img = coreimage::codecs::png::decode(&bytes).expect("png reference decode");
    assert_eq!(img.pixels.len(), img.width as usize * img.height as usize * 4);
    (img.width, img.height, img.pixels)
}

fn max_diff(a: &[u8], b: &[u8]) -> u8 {
    a.iter().zip(b.iter()).map(|(x, y)| x.abs_diff(*y)).max().unwrap_or(0)
}

fn mean_diff(a: &[u8], b: &[u8]) -> f32 {
    let sum: u64 = a.iter().zip(b.iter()).map(|(x, y)| x.abs_diff(*y) as u64).sum();
    sum as f32 / a.len() as f32
}

fn gradient_rgba(w: u32, h: u32) -> Vec<u8> {
    let mut px = Vec::with_capacity((w * h * 4) as usize);
    for y in 0..h {
        for x in 0..w {
            px.extend_from_slice(&[
                ((x * 4 + y * 2) % 256) as u8,
                ((y * 5 + x * 3) % 256) as u8,
                (((x * x + y * y) / 7) % 256) as u8,
                ((x * 7 + y * 11) % 256) as u8,
            ]);
        }
    }
    px
}

fn roundtrip(w: u32, h: u32, px: &[u8]) -> Vec<u8> {
    let enc = webp::encode(w, h, px, 90).expect("encode");
    assert!(webp::is_webp(&enc));
    let (dw, dh) = webp::dimensions(&enc).expect("dimensions");
    assert_eq!((dw, dh), (w, h));
    let dec = webp::decode(&enc).expect("decode");
    assert_eq!((dec.width, dec.height), (w, h));
    dec.pixels
}

// -- Magic / probing --

#[test]
fn rejects_non_webp() {
    assert!(!webp::is_webp(&[]));
    assert!(!webp::is_webp(b"RIFF"));
    assert!(!webp::is_webp(&data("gif_2bit.gif")));
    assert!(webp::dimensions(&[]).is_err());
    assert!(webp::decode(&[]).is_err());
    assert!(webp::decode(&data("gif_2bit.gif")).is_err());
}

#[test]
fn rejects_truncated_container() {
    let enc = webp::encode(8, 8, &vec![9u8; 8 * 8 * 4], 90).unwrap();
    for cut in [12, 13, 20, 24] {
        assert!(webp::decode(&enc[..cut]).is_err(), "cut {cut}");
    }
}

#[test]
fn rejects_inter_frame() {
    // Minimal RIFF + VP8 chunk with the inter-frame bit set.
    let mut f = b"RIFF....WEBP".to_vec();
    f[4..8].copy_from_slice(&18u32.to_le_bytes());
    f.extend_from_slice(b"VP8 ");
    f.extend_from_slice(&10u32.to_le_bytes());
    // Frame tag LSB = 1 (inter), rest zero.
    f.extend_from_slice(&[0x01, 0x00, 0x00, 0x9d, 0x01, 0x2a, 0x10, 0x00, 0x10, 0x00]);
    let err = webp::decode(&f).unwrap_err().to_string();
    assert!(err.contains("unsupported"), "got: {err}");
}

// -- Lossless roundtrips (exact) --

#[test]
fn roundtrip_solid() {
    let full = vec![200u8, 10, 30, 255].repeat(8 * 8);
    assert_eq!(roundtrip(8, 8, &full), full);
}

#[test]
fn roundtrip_gradient_odd_alpha() {
    let px = gradient_rgba(37, 23);
    assert_eq!(roundtrip(37, 23, &px), px);
}

#[test]
fn roundtrip_tiny() {
    assert_eq!(roundtrip(1, 1, &[1, 2, 3, 4]), vec![1, 2, 3, 4]);
    let px = gradient_rgba(2, 2);
    assert_eq!(roundtrip(2, 2, &px), px);
    let px = gradient_rgba(16, 16);
    assert_eq!(roundtrip(16, 16, &px), px);
}

#[test]
fn roundtrip_transparent() {
    let mut px = gradient_rgba(24, 18);
    for i in 0..px.len() / 4 {
        if i % 3 == 0 {
            px[i * 4 + 3] = 0;
        }
    }
    assert_eq!(roundtrip(24, 18, &px), px);
}

#[test]
fn encode_quality_validated() {
    let px = gradient_rgba(4, 4);
    assert!(webp::encode(4, 4, &px, 0).is_err());
    assert!(webp::encode(4, 4, &px, 101).is_err());
    // Lossless: quality does not change the bytes.
    let a = webp::encode(4, 4, &px, 1).unwrap();
    let b = webp::encode(4, 4, &px, 100).unwrap();
    assert_eq!(a, b);
}

#[test]
fn encode_bad_inputs() {
    assert!(webp::encode(0, 4, &[0u8; 64], 90).is_err());
    assert!(webp::encode(4, 0, &[0u8; 64], 90).is_err());
    assert!(webp::encode(4, 4, &[0u8; 63], 90).is_err());
    assert!(webp::encode(4, 4, &[0u8; 65], 90).is_err());
}

// -- Pillow reference fixtures --

#[test]
fn pillow_lossless_exact() {
    for (w, p) in [("webp_lossless_rgba.webp", "webp_lossless_rgba.png"), ("webp_odd_37x23_lossless.webp", "webp_odd_37x23_lossless.png")] {
        let bytes = data(w);
        assert!(webp::is_webp(&bytes), "{w}");
        let dec = webp::decode(&bytes).unwrap_or_else(|e| panic!("{w}: {e}"));
        let (rw, rh, rp) = ref_rgba(p);
        assert_eq!((dec.width, dec.height), (rw, rh), "{w} dims");
        assert_eq!(dec.pixels, rp, "{w} pixels differ");
        assert_eq!(webp::dimensions(&bytes).unwrap(), (rw, rh));
    }
}

#[test]
fn pillow_lossy_within_tolerance() {
    let bytes = data("webp_lossy_q80.webp");
    let dec = webp::decode(&bytes).expect("lossy decode");
    let (rw, rh, rp) = ref_rgba("webp_lossy_q80.png");
    assert_eq!((dec.width, dec.height), (rw, rh));
    let mx = max_diff(&dec.pixels, &rp);
    let mn = mean_diff(&dec.pixels, &rp);
    assert!(mx <= 32, "max diff {mx}");
    assert!(mn <= 4.0, "mean diff {mn}");
}

#[test]
fn pillow_lossy_alpha_within_tolerance() {
    let bytes = data("webp_lossy_alpha_q80.webp");
    let dec = webp::decode(&bytes).expect("lossy+alpha decode");
    let (rw, rh, rp) = ref_rgba("webp_lossy_alpha_q80.png");
    assert_eq!((dec.width, dec.height), (rw, rh));
    // Split color and alpha channels.
    let (dc, da): (Vec<u8>, Vec<u8>) = {
        let mut c = Vec::with_capacity(rw as usize * rh as usize * 3);
        let mut a = Vec::with_capacity(rw as usize * rh as usize);
        for i in 0..rw as usize * rh as usize {
            c.extend_from_slice(&dec.pixels[i * 4..i * 4 + 3]);
            a.push(dec.pixels[i * 4 + 3]);
        }
        (c, a)
    };
    let (rc, ra): (Vec<u8>, Vec<u8>) = {
        let mut c = Vec::with_capacity(rw as usize * rh as usize * 3);
        let mut a = Vec::with_capacity(rw as usize * rh as usize);
        for i in 0..rw as usize * rh as usize {
            c.extend_from_slice(&rp[i * 4..i * 4 + 3]);
            a.push(rp[i * 4 + 3]);
        }
        (c, a)
    };
    assert!(max_diff(&dc, &rc) <= 32, "color max {}", max_diff(&dc, &rc));
    assert!(mean_diff(&dc, &rc) <= 4.0, "color mean {}", mean_diff(&dc, &rc));
    assert!(max_diff(&da, &ra) <= 16, "alpha max {}", max_diff(&da, &ra));
}

#[test]
fn pillow_animated_first_frame() {
    let bytes = data("webp_animated.webp");
    let dec = webp::decode(&bytes).expect("animated decode");
    let (rw, rh, rp) = ref_rgba("webp_animated_first.png");
    assert_eq!((dec.width, dec.height), (rw, rh));
    assert!(mean_diff(&dec.pixels, &rp) <= 12.0, "mean {}", mean_diff(&dec.pixels, &rp));
}

// -- Extended container wrapping our own lossless payload --

fn riff_wrap_vp8x(vp8x: &[u8], inner_tag: &[u8; 4], inner: &[u8]) -> Vec<u8> {
    fn chunk(tag: &[u8], payload: &[u8], out: &mut Vec<u8>) {
        out.extend_from_slice(tag);
        out.extend_from_slice(&(payload.len() as u32).to_le_bytes());
        out.extend_from_slice(payload);
        if payload.len() & 1 == 1 {
            out.push(0);
        }
    }
    let mut chunks = Vec::new();
    chunk(b"VP8X", vp8x, &mut chunks);
    chunk(inner_tag, inner, &mut chunks);
    let mut f = b"RIFF....WEBP".to_vec();
    let riff_size = (4 + chunks.len()) as u32;
    f[4..8].copy_from_slice(&riff_size.to_le_bytes());
    f.extend_from_slice(&chunks);
    f
}

#[test]
fn extended_still_wraps_lossless() {
    let px = gradient_rgba(20, 12);
    let simple = webp::encode(20, 12, &px, 90).unwrap();
    // Strip the RIFF header to get the raw VP8L chunk payload.
    assert_eq!(&simple[0..4], b"RIFF");
    let inner_len = u32::from_le_bytes(simple[16..20].try_into().unwrap()) as usize;
    let vp8l_payload = &simple[20..20 + inner_len];
    let mut vp8x = vec![0u8; 10];
    vp8x[4..7].copy_from_slice(&(20u32 - 1).to_le_bytes()[..3]);
    vp8x[7..10].copy_from_slice(&(12u32 - 1).to_le_bytes()[..3]);
    let f = riff_wrap_vp8x(&vp8x, b"VP8L", vp8l_payload);
    let dec = webp::decode(&f).expect("extended still");
    assert_eq!((dec.width, dec.height), (20, 12));
    assert_eq!(dec.pixels, px);
}

// -- TiImage integration --

#[test]
fn tiimage_webp_roundtrip() {
    use coreimage::{ImageFormat, TiImage};
    let px = gradient_rgba(32, 24);
    let img = TiImage::from_rgba(coreimage::RgbaImage::from_raw(32, 24, px.clone()).unwrap());
    let bytes = img.to_bytes(ImageFormat::WebP, 90).unwrap();
    let back = TiImage::from_bytes(&bytes).unwrap();
    assert_eq!(back.dimensions(), (32, 24));
    assert_eq!(back.as_rgba().as_raw(), px.as_slice());
    assert_eq!(back.source_format(), Some(ImageFormat::WebP));
    let explicit = TiImage::from_bytes_with_format(&bytes, ImageFormat::WebP).unwrap();
    assert_eq!(explicit.as_rgba().as_raw(), px.as_slice());
    assert_eq!(
        coreimage::io::probe_format_from_bytes(&bytes).unwrap(),
        ImageFormat::WebP
    );
    let meta = coreimage::io::metadata_from_bytes(&bytes).unwrap();
    assert_eq!((meta.width, meta.height), (32, 24));
    assert_eq!(meta.format, Some(ImageFormat::WebP));
}

#[test]
fn tiimage_webp_file() {    use coreimage::{ImageFormat, TiImage};
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("t.webP");
    let px = gradient_rgba(37, 23);
    let img = TiImage::from_rgba(coreimage::RgbaImage::from_raw(37, 23, px.clone()).unwrap());
    img.save(path.to_str().unwrap(), ImageFormat::WebP, 80).unwrap();
    let back = TiImage::load(path.to_str().unwrap()).unwrap();
    assert_eq!(back.dimensions(), (37, 23));
    assert_eq!(back.as_rgba().as_raw(), px.as_slice());
    assert_eq!(TiImage::probe_format(path.to_str().unwrap()).unwrap(), ImageFormat::WebP);
    let meta = TiImage::probe_metadata(path.to_str().unwrap()).unwrap();
    assert_eq!((meta.width, meta.height), (37, 23));
}

/// Local differential-debug helper: dumps our decode of Pillow fixtures
/// to /tmp for comparison against Pillow. Ignored in normal runs.
#[test]
#[ignore]
fn debug_dump_fixtures() {
    for name in ["webp_animated.webp"] {
        let bytes = data(name);
        match webp::decode(&bytes) {
            Ok(d) => {
                let out = format!("/tmp/ours_{}.raw", name.replace(".webp", ""));
                std::fs::write(&out, &d.pixels).unwrap();
                eprintln!("{name}: {}x{} -> {out}", d.width, d.height);
                let mut hist = [0u32; 4];
                for px in d.pixels.chunks_exact(4) {
                    hist[0] += px[0] as u32;
                    hist[1] += px[1] as u32;
                    hist[2] += px[2] as u32;
                    hist[3] += px[3] as u32;
                }
                let n = (d.width * d.height) as u32;
                eprintln!("means: {:?}", hist.map(|s| s / n));
            }
            Err(e) => eprintln!("{name}: ERROR {e}"),
        }
    }
}
