#!/usr/bin/env python3
"""Generate Rust tables for the AV1 decoder from the AV1 specification.

Usage:
    python3 gen_av1_spec_tables.py <av1-spec.html> <out-dir>

Writes two generated modules into <out-dir>:

    cdf_default.rs   default CDF tables (section 9.4)
    spec_consts.rs   numeric constants (symbols and abbreviated terms)

The AV1 Bitstream & Decoding Process Specification (AOMedia) is published under
CC0 1.0, so the normative tables reproduced here carry no license obligation.
"""
import os
import re
import sys


def _strip(html):
    txt = re.sub(r'<[^>]+>', ' ', html)
    for a, b in (('&gt;', '>'), ('&lt;', '<'), ('&amp;', '&'), ('&nbsp;', ' ')):
        txt = txt.replace(a, b)
    return txt


def _cells(row):
    return [_strip(c).strip() for c in re.findall(r'<t[dh][^>]*>(.*?)</t[dh]>', row, re.S)]


def _collect_rows(html):
    """Yield (name, expression) for every constant table row in the document."""
    for row in re.findall(r'<tr[^>]*>(.*?)</tr>', html, re.S):
        cells = _cells(row)
        if len(cells) < 2:
            continue
        name, value = cells[0], cells[1]
        if not re.fullmatch(r'[A-Z][A-Z0-9_]*', name):
            continue
        if not re.fullmatch(r'[0-9A-Za-z_+\-*/() \t]+', value):
            continue
        yield name, value


def spec_constants(html):
    start = html.index('id="symbols-and-abbreviated-terms"')
    m = re.compile(r'<h[23][^>]*id="(?!symbols-and-abbreviated-terms)[^"]+"').search(html, start + 10)
    end = m.start() if m else len(html)
    exprs = dict(_collect_rows(html[start:end]))
    # Not listed in the symbols table, but implied by Remap_Lr_Type and the
    # restoration_type syntax element: RESTORE_NONE 0, SWITCHABLE 1, WIENER 2,
    # SGRPROJ 3 remap to 0, 2, 3, 4.
    exprs.setdefault('RESTORE_SWITCHABLE', '2')
    values = {}

    def resolve(pool):
        for _ in range(12):
            progress = False
            for name, expr in pool.items():
                if name in values:
                    continue
                try:
                    values[name] = int(eval(expr, {'__builtins__': {}}, dict(values)))
                    progress = True
                except Exception:
                    pass
            if not progress:
                return

    resolve(exprs)
    if 'MAX_TX_DEPTH' not in values:
        exprs.update(dict(_collect_rows(html[:start])))
        resolve(exprs)
    return values


def rust_cdf_name(spec_name):
    body = spec_name[len('Default_'):]
    if body.endswith('_Cdf'):
        body = body[:-len('_Cdf')]
    return 'DEFAULT_' + body.upper()


def cdf_tables(txt):
    tables = []
    pos = 0
    pattern = re.compile(r'(Default_[A-Za-z0-9_]+)\s*((?:\[[^\]]*\]\s*)+)=\s*')
    while True:
        m = pattern.search(txt, pos)
        if not m:
            break
        name = m.group(1)
        dims_src = m.group(2)
        brace = txt.index('{', m.end())
        depth = 0
        i = brace
        while True:
            if txt[i] == '{':
                depth += 1
            elif txt[i] == '}':
                depth -= 1
                if depth == 0:
                    break
            i += 1
        body = txt[brace + 1:i]
        pos = i + 1
        values = [int(eval(tok, {'__builtins__': {}}, {}))
                  for tok in re.findall(r'\d+(?:\s*[*+]\s*\d+)*', body)]
        dims = []
        for expr in re.findall(r'\[([^\]]*)\]', dims_src):
            expr = expr.strip()
            try:
                dims.append(int(eval(expr, {'__builtins__': {}}, dict(consts))))
            except Exception:
                sys.exit('unresolved dimension %r in %s' % (expr, name))
        size = 1
        for d in dims:
            size *= d
        if size != len(values):
            # The specification has a known typo here: the declared dimension of
            # Default_Restoration_Type_Cdf is RESTORE_SWITCHABLE + 1 while the
            # table holds RESTORE_SWITCHABLE + 2 entries. Trust the data and widen
            # the last dimension when the remainder divides evenly.
            head = 1
            for d in dims[:-1]:
                head *= d
            if dims and len(values) % head == 0:
                print('note: %s declares %s but holds %d values, widening last '
                      'dimension to %d' % (name, dims, len(values), len(values) // head))
                dims[-1] = len(values) // head
            else:
                sys.exit('size mismatch for %s: dims %s = %d, found %d values'
                         % (name, dims, size, len(values)))
        tables.append((name, dims, values))
    return tables


HEADER = ('// @generated by tools/gen_av1_spec_tables.py from the AV1\n'
          '// specification (CC0 1.0). Do not edit.\n')


def write_cdfs(path, tables):
    lines = [HEADER, '//',
             '// Each entry is `(&[u16], &[usize])`: the flat table and its dimensions,',
             '// exactly as declared in section 9.4 of the specification.', '',
             '/// Flat default tables with their dimensions, keyed by specification name.',
             'pub const DEFAULTS: &[(&str, &[u16], &[usize])] = &[']
    for name, dims, values in tables:
        lines.append('    ("%s", &[%s], &[%s]),'
                     % (name, ', '.join(map(str, values)), ', '.join(map(str, dims))))
    lines += ['];', '']
    for name, dims, values in tables:
        lines.append('/// `%s` with dimensions %s.' % (name, dims))
        lines.append('pub const %s: (&[u16], &[usize]) = (' % rust_cdf_name(name))
        lines.append('    &[')
        for i in range(0, len(values), 12):
            lines.append('        ' + ', '.join(map(str, values[i:i + 12])) + ',')
        lines.append('    ],')
        lines.append('    &[%s],' % ', '.join(map(str, dims)))
        lines.append(');')
        lines.append('')
    lines.append('/// Look up a default table by its specification name.')
    lines.append("pub fn by_name(name: &str) -> Option<(&'static [u16], &'static [usize])> {")
    lines += ['    DEFAULTS', '        .iter()', '        .find(|(n, _, _)| *n == name)',
              '        .map(|(_, d, s)| (*d, *s))', '}', '']
    open(path, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))


def write_consts(path, consts):
    lines = [HEADER, '//',
             '// Numeric constants from the symbols and abbreviated terms section.',
             '// Names match the specification verbatim.', '']
    for name in sorted(consts):
        lines.append('/// %s' % name)
        lines.append('pub const %s: i32 = %d;' % (name, consts[name]))
    open(path, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    html = open(sys.argv[1], encoding='utf-8', errors='replace').read()
    global consts
    consts = spec_constants(html)
    start = html.index('id="default-cdf-tables"')
    m = re.compile(r'<h[23][^>]*id="(?!default-cdf-tables)[^"]+"').search(html, start + 10)
    end = m.start() if m else len(html)
    txt = re.sub(r'<[^>]+>', '', html[start:end])
    for a, b in (('&gt;', '>'), ('&lt;', '<'), ('&amp;', '&'), ('&nbsp;', ' ')):
        txt = txt.replace(a, b)
    tables = cdf_tables(txt)
    os.makedirs(sys.argv[2], exist_ok=True)
    write_cdfs(os.path.join(sys.argv[2], 'cdf_default.rs'), tables)
    write_consts(os.path.join(sys.argv[2], 'spec_consts.rs'), consts)
    print('cdf tables: %d, symbols: %d, constants: %d'
          % (len(tables), sum(len(v) for _, _, v in tables), len(consts)))


if __name__ == '__main__':
    main()