#!/usr/bin/env python3
"""Generate src/codecs/av1/cdf.rs from the generated default CDF tables.

Usage:
    python3 tools/gen_cdf_model.py src/codecs/av1/cdf_default.rs src/codecs/av1/cdf.rs

The symbol decoder adapts a private copy of every default table per tile, so the
model owns the mutable tables and hands out the slice of one context at a time.
Coefficient tables are indexed by `base_q_idx`: `init_symbol( sz )` seeds them
with the first slice and `init_coeff_cdfs( )` replaces it with the slice of the
current frame.
"""
import re
import sys

# Tables re-initialised per tile by init_coeff_cdfs( ) from a base_q_idx slice.
COEFF = [
    'DEFAULT_TXB_SKIP',
    'DEFAULT_EOB_PT_16',
    'DEFAULT_EOB_PT_32',
    'DEFAULT_EOB_PT_64',
    'DEFAULT_EOB_PT_128',
    'DEFAULT_EOB_PT_256',
    'DEFAULT_EOB_PT_512',
    'DEFAULT_EOB_PT_1024',
    'DEFAULT_EOB_EXTRA',
    'DEFAULT_DC_SIGN',
    'DEFAULT_COEFF_BASE_EOB',
    'DEFAULT_COEFF_BASE',
    'DEFAULT_COEFF_BR',
]


def parse_tables(path):
    """Return `(name, dimensions, values)` of every default table."""
    src = open(path, encoding='utf-8').read()
    tables = []
    for m in re.finditer(
            r'pub const (DEFAULT_[A-Z0-9_]+): \(&\[u16\], &\[usize\]\) = \((.*?)\n\);',
            src, re.S):
        body = m.group(2)
        dims = [int(x) for x in re.search(r'&\[([0-9, ]+)\],$', body, re.M).group(1).split(',')]
        values = [int(x) for x in re.findall(r'\d+', body.split('],')[0])]
        tables.append((m.group(1), dims, values))
    return tables


def field_of(name):
    if name in COEFF:
        return name[len('DEFAULT_'):].lower()
    return name[len('DEFAULT_'):].lower()


def emit_array(values, indent):
    out = []
    for i in range(0, len(values), 12):
        out.append(indent + ', '.join(str(v) for v in values[i:i + 12]) + ',')
    return out


def generate(tables):
    lines = [
        '// @generated by tools/gen_cdf_model.py from cdf_default.rs. Do not edit.',
        '//',
        '// The symbol decoder adapts a private copy of every default table per tile,',
        '// so this model owns the mutable tables and hands out one context slice at a',
        '// time.',
        '',
        'use super::cdf_default as def;',
        '',
        '/// One mutable CDF per default table of section 9.4.',
        'pub struct Cdfs {',
    ]
    for name, dims, _values in tables:
        if name in COEFF:
            dims = dims[1:]
        total = 1
        for d in dims:
            total *= d
        lines.append('    %s: [u16; %d],' % (field_of(name), total))
    lines += ['}', '', 'impl Default for Cdfs {', '    fn default() -> Self {',
              '        Cdfs::new()', '    }', '}', '', 'impl Cdfs {']

    lines += [
        '    /// Copy of every default table, `init_symbol( sz )` plus',
        '    /// `init_non_coeff_cdfs( )`. Coefficient tables start with the first',
        '    /// `base_q_idx` slice.',
        '    pub fn new() -> Self {',
        '        Self {',
    ]
    for name, dims, values in tables:
        field = field_of(name)
        if name in COEFF:
            total = 1
            for d in dims[1:]:
                total *= d
            lines.append('            %s: [' % field)
            lines += emit_array(values[:total], '                ')
            lines.append('            ],')
        else:
            lines.append('            %s: def::%s.0.try_into().expect("default table size"),'
                         % (field, name))
    lines += [
        '        }',
        '    }',
        '',
        '    /// `init_coeff_cdfs( )`: the coefficient tables depend on base_q_idx.',
        '    pub fn init_coeff(&mut self, base_q_idx: u32) {',
        '        let idx: usize = if base_q_idx <= 20 {',
        '            0',
        '        } else if base_q_idx <= 60 {',
        '            1',
        '        } else if base_q_idx <= 120 {',
        '            2',
        '        } else {',
        '            3',
        '        };',
    ]
    for name in COEFF:
        lines.append('        copy_idx(&def::%s, idx, &mut self.%s);' % (name, field_of(name)))
    lines += [
        '    }',
        '}',
        '',
        '/// Copy one `base_q_idx` slice of a default table into a model table.',
        'fn copy_idx(',
        "    default: &(&'static [u16], &'static [usize]),",
        '    idx: usize,',
        '    out: &mut [u16],',
        ') {',
        '    let (values, dims) = *default;',
        '    let stride: usize = dims[1..].iter().product();',
        '    let start = idx * stride;',
        '    out.copy_from_slice(&values[start..start + stride]);',
        '}',
        '',
        '/// One context slice of every table, named after the specification.',
        'impl Cdfs {',
    ]
    for name, dims, _values in tables:
        field = field_of(name)
        if name in COEFF:
            dims = dims[1:]
        args = ', '.join('c%d: usize' % i for i in range(len(dims) - 1))
        params = (', ' + args) if args else ''
        stride = []
        acc = 1
        for d in reversed(dims[1:]):
            stride.append(acc)
            acc *= d
        expr = ' + '.join('c%d * %d' % (i, stride[i]) for i in range(len(dims) - 1)) or '0'
        lines += [
            '    #[inline]',
            '    pub fn %s(&mut self%s) -> &mut [u16] {' % (field, params),
            '        let base = %s;' % expr,
            '        &mut self.%s[base..base + %d]' % (field, dims[-1]),
            '    }',
        ]
    lines += ['}', '']
    return '\n'.join(lines)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    tables = parse_tables(sys.argv[1])
    open(sys.argv[2], 'w', encoding='utf-8', newline='\n').write(generate(tables) + '\n')
    print('tables %d, fields written to %s' % (len(tables), sys.argv[2]))


if __name__ == '__main__':
    main()